FileVersion = 1

[Project]
Name = "libwebp-beef"
DefaultNamespace = "libwebp"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\libwebp_d.lib", "$(ProjectDir)\\libs\\windows\\x64\\libsharpyuv_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\libwebp.lib", "$(ProjectDir)\\libs\\windows\\x64\\libsharpyuv.lib"]