FileVersion = 1

[Project]
Name = "libwebp-beef"
DefaultNamespace = "libwebp"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\debug\\libwebp.lib", "$(ProjectDir)\\libs\\debug\\libsharpyuv.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\release\\libwebp.lib", "$(ProjectDir)\\libs\\release\\libsharpyuv.lib"]